# -*- coding: utf-8 -*-
"""web_scraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F2iQdMl3xtzjOLS0jJZ8xfFosoHzzWyy
"""

#https://github.com/simonw/ca-fires-history/blob/main/.github/workflows/scrape.yml
import requests
from bs4 import BeautifulSoup

# wrap text in cells
# see: https://stackoverflow.com/questions/58890109/line-wrapping-in-collaboratory-google-results
from IPython.display import HTML, display

def set_css():
  display(HTML('''
  <style>
    pre {
        white-space: pre-wrap;
    }
  </style>
  '''))
get_ipython().events.register('pre_run_cell', set_css)

url = "https://github.com/bitcoin/bitcoin/graphs/contributors"
url2 = "https://nvd.nist.gov/vuln/full-listing"
page = requests.get(url2)

soup = BeautifulSoup(page.text, 'html.parser')
print(soup.prettify())

soup.p

